export enum HomeStateActionTypes {
  SET_IS_IMPORTING,
  SET_STROKE_COLOR,
  SET_FILL_COLOR,
  SET_HISTORY,
  ADD_HISTORY,
  UNDO,
  REDO,
  SET_TOOL,
  SET_STROKE_SIZE,
  SET_ZOOM,
  SET_SELECTED_SHAPE,
}
