export enum ToolTypes {
  DRAW = "DRAW",
  CIRCLE = "CIRCLE",
  SQUARE = "SQUARE",
  RECTANGLE = "RECTANGLE",
  UP_TRIANGLE = "UP_TRIANGLE",
  RIGHT_TRIANGLE = "RIGHT_TRIANGLE",
  DOWN_TRIANGLE = "DOWN_TRIANGLE",
  LEFT_TRIANGLE = "LEFT_TRIANGLE",
  PAN = "PAN",
}
