export enum ToolNames {
  CIRCLE = "CIRCLE",
  SQUARE = "SQUARE",
  UP_TRIANGLE = "UP_TRIANGLE",
  RIGHT_TRIANGLE = "RIGHT_TRIANGLE",
  DOWN_TRIANGLE = "DOWN_TRIANGLE",
  LEFT_TRIANGLE = "LEFT_TRIANGLE",
  RECTANGLE = "RECTANGLE",
  PEN = "PEN",
}
